name: build
on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Install dependencies
        run: npm i
      - name: Build FlowOS
        run: npm run build